### PR TITLE
Fix technologist pdf, update jobs email

### PR DESCRIPTION
**Pull request by srstsavage**

### CODE REVIEW

**Comment by srstsavage** [comment]
@iamchrisser Please review and merge.

**Comment by iamchrisser** [comment]
I didn't realize you created a new branch for this. I saw the comment and made the same changes and pushed to master.

**Comment by srstsavage** [comment]
@iamchrisser DId you replace the PDF also?

**Comment by iamchrisser** [comment]
I did replace the pdf.

**Pull request closed without merging**
